[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.9.0",
    "pydantic-settings>=2.8.1",
    "pydantic>=2.11.1",
    "openai-whisper>=20240930",
]
