"""Add models for LLMModel Responses

Revision ID: d8d4585a31b1
Revises: dd4c54e0aac6
Create Date: 2024-12-03 15:55:22.200896

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8d4585a31b1'
down_revision = 'dd4c54e0aac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmodel_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('answer_to_msg_with_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answer_to_msg_with_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llmodel_response')
    # ### end Alembic commands ###
