"""change 'text' column to 'message' in ChatMessage

Revision ID: dd4c54e0aac6
Revises: c7eef5fef933
Create Date: 2024-11-23 19:02:26.467377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd4c54e0aac6'
down_revision = 'c7eef5fef933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('message', sa.Text(), nullable=True))
    op.drop_column('chat_message', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chat_message', 'message')
    # ### end Alembic commands ###
